baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'portfolio'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
